In [1]:
import torch

# torch.rand() produces values lying between 0 and 1 from uniform distribution

In [2]:
torch.rand(1)

tensor([0.3096])

# torch.randn() produces values with a mean of 0 and a standard deviation of 1. The values can be both positive or negative and it generate values from uniform distribution

In [3]:
x = torch.randn(3, requires_grad = True)

In [4]:
x

tensor([-0.5923, -1.1908, -0.8394], requires_grad=True)

In [5]:
y = x + 2

In [6]:
y

tensor([1.4077, 0.8092, 1.1606], grad_fn=<AddBackward0>)

In [7]:
z = y * y * 2

In [8]:
v = torch.randn(3)

In [9]:
v

tensor([ 0.2416,  0.4982, -0.1073])

In [10]:
# z = z.mean()

In [11]:
z

tensor([3.9630, 1.3095, 2.6941], grad_fn=<MulBackward0>)

# While calling the backward function, remember that if the tensor is a scalar (i.e., it contains only one value), you don't need to pass any arguments. However, if the tensor is a vector, you must create a vector of the same size and pass it to the backward function to compute the gradients

In [12]:
z.backward(v) # dz/dx

In [13]:
x.grad

tensor([ 1.3603,  1.6125, -0.4983])

# there are 3 ways to stop torch from making gradient functions and tracking the history in our computational graph

## 1 - variable.requires_grad_(False)

In [14]:
x.requires_grad_(False)

tensor([-0.5923, -1.1908, -0.8394])

## 2 - variable_name.detach()

In [15]:
y = x.detach()

In [16]:
y

tensor([-0.5923, -1.1908, -0.8394])

## 3 - with torch.no_grad():

In [17]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([1.4077, 0.8092, 1.1606])


In [18]:
y

tensor([1.4077, 0.8092, 1.1606])

In [41]:
weights = torch.ones(4, requires_grad = True)

In [44]:
[weights]

[tensor([1., 1., 1., 1.], requires_grad=True)]

In [46]:
optimizer = torch.optim.SGD([weights], lr = 0.01)

In [48]:
optimizer.step()
optimizer.zero_grad()

In [ ]:
for epoch in range(3):
    print(f"epoch # {epoch}")
    model_output = (weights * 3).sum()
    print(model_output)
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    print()