In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(n_input_features, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

In [3]:
model = Model(n_input_features =  6)

In [4]:
model.state_dict()

OrderedDict([('model.0.weight',
              tensor([[-0.1254, -0.3106,  0.2015, -0.1332, -0.0418,  0.3071]])),
             ('model.0.bias', tensor([-0.0534]))])

In [5]:
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [6]:
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.01,
   'momentum': 0,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'maximize': False,
   'foreach': None,
   'differentiable': False,
   'params': [0, 1]}]}

# For saving checkpoint

In [7]:
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict()
}

In [8]:
torch.save(checkpoint, "./saved_models/tutorial_checkpoint.pth")

# For loading checkpoint

In [9]:
loaded_checkpoint = torch.load("./saved_models/tutorial_checkpoint.pth")

In [10]:
loaded_checkpoint

{'epoch': 90,
 'model_state': OrderedDict([('model.0.weight',
               tensor([[-0.1254, -0.3106,  0.2015, -0.1332, -0.0418,  0.3071]])),
              ('model.0.bias', tensor([-0.0534]))]),
 'optim_state': {'state': {},
  'param_groups': [{'lr': 0.01,
    'momentum': 0,
    'dampening': 0,
    'weight_decay': 0,
    'nesterov': False,
    'maximize': False,
    'foreach': None,
    'differentiable': False,
    'params': [0, 1]}]}}

## defining epoch, model, and optimizer again because we will load the saved values in them

In [11]:
model = Model(n_input_features =  6)

In [12]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0)

## loading saved values in the defined epoch, model, and optimizer

In [13]:
epoch = loaded_checkpoint["epoch"]

In [14]:
model.load_state_dict(loaded_checkpoint["model_state"])

<All keys matched successfully>

In [15]:
optimizer.load_state_dict(loaded_checkpoint["optim_state"])

In [16]:
epoch, model.state_dict(), optimizer.state_dict()

(90,
 OrderedDict([('model.0.weight',
               tensor([[-0.1254, -0.3106,  0.2015, -0.1332, -0.0418,  0.3071]])),
              ('model.0.bias', tensor([-0.0534]))]),
 {'state': {},
  'param_groups': [{'lr': 0.01,
    'momentum': 0,
    'dampening': 0,
    'weight_decay': 0,
    'nesterov': False,
    'maximize': False,
    'foreach': None,
    'differentiable': False,
    'params': [0, 1]}]})

# Lazy Method

In [17]:
# FILE = "./saved_models/tutorial_lazy_method_model.pth"

In [18]:
# torch.save(model, FILE)

In [19]:
# model = torch.load(FILE)

In [20]:
# model

## by saving model from this method the model size if 3KB

# Recommended Method

In [21]:
FILE = "./saved_models/tutorial_recommended_method_model.pth"

In [22]:
torch.save(model.state_dict(), FILE)

## for loading model, first we have to define it

In [23]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(n_input_features, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

In [24]:
loaded_model = Model(n_input_features =  6)

In [25]:
loaded_model.load_state_dict(torch.load(FILE))

<All keys matched successfully>

In [26]:
loaded_model.eval()

Model(
  (model): Sequential(
    (0): Linear(in_features=6, out_features=1, bias=True)
    (1): Sigmoid()
  )
)

## by saving model from this method the model size if 2KB thats why it is the recommened method