In [13]:
import numpy as np
import torch
import torch.nn as nn

# softmax from scratch

In [2]:
def softmax(array_of_scores):
    return np.exp(array_of_scores) / np.sum(np.exp(array_of_scores), axis = 0)

In [3]:
x = np.array([2.0, 1.0, 0.1])

In [4]:
softmax(x)

array([0.65900114, 0.24243297, 0.09856589])

# torch's tensor

In [5]:
x = torch.tensor([2.0, 1.0, 0.1])

In [6]:
torch.softmax(x, dim = 0)

tensor([0.6590, 0.2424, 0.0986])

# cross entropy from scratch

In [10]:
def cross_entropy(predictions, y):
    return (-1 / y.shape[0]) * (np.sum(y * np.log(predictions)))

In [11]:
y = np.array([1., 0., 0.])
predictions = np.array([0.7, 0.2, 0.1])

In [12]:
cross_entropy(predictions, y)

0.11889164797957748

# torch's cross entropy

In [14]:
loss = nn.CrossEntropyLoss() # should not apply softmax layer in the last

In [33]:
y = torch.tensor([2, 0, 1])

In [34]:
y_pred_good = torch.tensor(
    [[0.1, 0.2, 3.9], # predict class 2
    [1.2, 0.1, 0.3], # predict class 0
    [0.3, 2.2, 0.2]]) # predict class 1

y_pred_bad = torch.tensor(
    [[0.9, 0.2, 0.1],
    [0.1, 0.3, 1.5],
    [1.2, 0.2, 0.5]])

In [35]:
print(loss(y_pred_good, y).item())
loss(y_pred_bad, y).item()

0.28342217206954956


1.6418448686599731

In [36]:
print(torch.max(y_pred_good, 1)[1]) # returns the maximum value of the tensor and its index
torch.max(y_pred_bad, 1)[1]

tensor([2, 0, 1])


tensor([0, 2, 0])

In [76]:
class NeuralNetMultiClass(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNetMultiClass, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        return self.linear2(out)

In [77]:
model1 = NeuralNetMultiClass(input_size = 28 * 28, hidden_size = 64, num_classes = 3)

In [78]:
criterion_for_multiclass = nn.CrossEntropyLoss() # applies softmax

In [83]:
class NeuralNetBinaryClass(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNetBinaryClass, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        prediction = torch.sigmoid(out)
        return prediction

In [84]:
model2 = NeuralNetBinaryClass(input_size = 28 * 28, hidden_size = 64)

In [85]:
criterion_for_binaryclass = nn.BCELoss()