In [33]:
import torch
import numpy as np

In [2]:
torch.empty(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
torch.rand(3)

tensor([0.9734, 0.8480, 0.4130])

In [4]:
torch.zeros(3)

tensor([0., 0., 0.])

In [5]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
tensor = torch.ones(3, 3, dtype = torch.int)

In [7]:
tensor

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [8]:
tensor.size()

torch.Size([3, 3])

In [9]:
torch.tensor([1.05, 2, 3])

tensor([1.0500, 2.0000, 3.0000])

In [10]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [11]:
z = x + y

In [12]:
z

tensor([5, 7, 9])

In [13]:
torch.add(x, y)

tensor([5, 7, 9])

# updates y
## point to remember: any function with a trailing underscore(_) will act as an inplace function and it updates the value of what is inside of it

In [14]:
y.add_(x)

tensor([5, 7, 9])

In [15]:
y

tensor([5, 7, 9])

In [16]:
torch.sub(x, y)

tensor([-4, -5, -6])

In [17]:
torch.mul(x, y)

tensor([ 5, 14, 27])

In [18]:
torch.div(x, y)

tensor([0.2000, 0.2857, 0.3333])

In [19]:
test_tensor = torch.tensor([[1, 2, 3],
                            [4, 5, 6]])

In [20]:
test_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
test_tensor.size()

torch.Size([2, 3])

In [32]:
test_tensor.shape

torch.Size([2, 3])

In [21]:
test_tensor[0, 0]

tensor(1)

In [22]:
test_tensor[0, 0].item()

1

In [27]:
test_tensor.view(-1, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

# converting a tensor into numpy

In [40]:
test_array = test_tensor.numpy()

In [41]:
test_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [42]:
test_array

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [43]:
type(test_tensor), type(test_array)

(torch.Tensor, numpy.ndarray)

In [46]:
test_tensor.add_(1)

tensor([[2, 3, 4],
        [5, 6, 7]])

In [47]:
test_tensor

tensor([[2, 3, 4],
        [5, 6, 7]])

In [48]:
test_array

array([[2, 3, 4],
       [5, 6, 7]], dtype=int64)

# we conclude that, if you make an array from a pre-defined tensor and vice versa, then whatever changes you have done to the pre-defined one will automatically apply to the other one

# converting a array into tensor

In [49]:
a = np.ones(5)

In [50]:
a

array([1., 1., 1., 1., 1.])

In [55]:
b = torch.from_numpy(a)

In [54]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [56]:
a += 1

In [57]:
a

array([2., 2., 2., 2., 2.])

In [58]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

# numpy can only handle CPU tensors, we can not convert a GPU tensor to a numpy array

In [60]:
torch.ones(5, requires_grad = True)

tensor([1., 1., 1., 1., 1.], requires_grad=True)

# requires_grad = True will tell pytorch that it will need to calculate gradients for this tensor later in our optimization steps, if we want to optimize any variable so we have to pass requires_grad as True