# steps
## 1 - deign model (input size, output size, forward pass)
## 2 - construct the loss and optimizer
## 3 - training loop
### - forward pass: compute predictions
### - backward pass: gradients
### - update weights

In [1]:
import torch
import torch.nn as nn

In [2]:
X = torch.tensor([i for i in range(1, 5)], dtype = torch.float32).view(-1, 1)
y = torch.tensor([i * 2 for i in range(1, 5)], dtype = torch.float32).view(-1, 1)

In [3]:
X_test = torch.tensor([5], dtype = torch.float32)

In [4]:
X, y, X_test

(tensor([[1.],
         [2.],
         [3.],
         [4.]]),
 tensor([[2.],
         [4.],
         [6.],
         [8.]]),
 tensor([5.]))

In [5]:
n_samples, n_features = X.shape

In [6]:
n_samples, n_features

(4, 1)

In [7]:
output_size = y.shape[1]

In [8]:
output_size

1

In [9]:
input_size = n_features
output_size = output_size

In [10]:
# model = nn.Linear(input_size, output_size)

In [11]:
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.linear(x)

In [12]:
model = LinearRegression(input_size, output_size)

In [13]:
print(f"prediction for f(5) before training: {model(X_test).item():.3f}")

prediction for f(5) before training: -4.118


In [14]:
learning_rate = 0.01
epochs = 100

In [15]:
loss = nn.MSELoss()

In [16]:
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [17]:
for epoch in range(1, epochs + 1):
    predictions = model(X)
    l = loss(predictions, y)
    l.backward() # dl/dw
    optimizer.step() # optimization step, updates weights
    optimizer.zero_grad() # set the weight to zero
    if epoch % 10 == 0:
        print(f"Epoch # {epoch}")
        print(f"X: {X}")
        print(f"y: {y}")
        print(f"Predictions: {predictions}")
        print(f"Loss: {l:.3f}")
        [weight, bias] = model.parameters()
        print(f"Weight: {weight[0][0].item():.3f}")
        print(f"Bias: {bias[0].item():.3f}")
        print()

Epoch # 10
X: tensor([[1.],
        [2.],
        [3.],
        [4.]])
y: tensor([[2.],
        [4.],
        [6.],
        [8.]])
Predictions: tensor([[1.2561],
        [2.7726],
        [4.2892],
        [5.8057]], grad_fn=<AddmmBackward0>)
Loss: 2.450
Weight: 1.602
Bias: -0.231

Epoch # 20
X: tensor([[1.],
        [2.],
        [3.],
        [4.]])
y: tensor([[2.],
        [4.],
        [6.],
        [8.]])
Predictions: tensor([[1.8344],
        [3.7803],
        [5.7262],
        [7.6722]], grad_fn=<AddmmBackward0>)
Loss: 0.065
Weight: 1.960
Bias: -0.107

Epoch # 30
X: tensor([[1.],
        [2.],
        [3.],
        [4.]])
y: tensor([[2.],
        [4.],
        [6.],
        [8.]])
Predictions: tensor([[1.9287],
        [3.9430],
        [5.9573],
        [7.9716]], grad_fn=<AddmmBackward0>)
Loss: 0.003
Weight: 2.016
Bias: -0.085

Epoch # 40
X: tensor([[1.],
        [2.],
        [3.],
        [4.]])
y: tensor([[2.],
        [4.],
        [6.],
        [8.]])
Predictions: tensor(

In [18]:
print(f"prediction for f(5) before training: {model(X_test).item():.3f}")

prediction for f(5) before training: 10.046
